version: '3'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: xvote
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "80:3000"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/xvote?schema=public
      NEXTAUTH_SECRET: supersecretkey
      NEXTAUTH_URL: http://voteflow.app
    depends_on:
      - db
    # server.js is created by next build from the standalone output
    command: >
      sh -c "npx prisma generate && node server.js"

volumes:
  db_data:

